config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :about, to: 'static_pages#about'
  root to: "landing#index"


  resources :items , only: [:index, :show, :edit]

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :ordered_items, only: [:add, :create]

  resources :orders, only: [:create]
  resources :carts, only: [:index, :add, :show, :edit, :remove]

  resources :checkouts, only: [:new, :create]


  post :add, to: 'carts#add'
  post :remove, to: 'carts#remove'

  match 'auth/:provider/callback', to: 'omniauth#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'omniauth#destroy', as: 'signout', via: [:get, :post]
end

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">
  <% flash.each do |k,v| %>
    <section class="flash-messages">
      <div class="alert alert-<%=k%>">
        <button type="button" class="close" data-dismiss="alert">
          &times;
        </button>
        <div class="message">
          <%= display_message(v) %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">DayShop</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">About</a></li>
        <li><%= link_to fa_icon("shopping-cart 1x"), carts_path, class: 'white shadowed link-styling' %></li>
        <li><a href="/items">Shop</a></li>

        <% if current_user %>
          <% if current_user.admin? %>
            <li><%= link_to "Admin", rails_admin_path, class: 'white shadowed link-styling' %></li>
          <% end %>
          <li><%= link_to "#{current_user.username}", edit_user_path(current_user), class: 'white shadowed link-styling' %></li>
          <li><%= link_to "Log-out", session_path(current_user), method: :Delete, class: 'white shadowed link-styling' %></li>
        <% else %>
          <li><a class="pressable" data-toggle="modal" data-target="#register">Register</a></li>
          <li><a class="pressable" data-toggle="modal" data-target="#log-in">Log-in</a></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_login.html.erb
<div class="modal fade" id="log-in">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="form">
            <%= form_for(:user, url: sessions_path, html: { id: "user-create-form" }) do |f| %>
              <h1 class="text-center">
                Log In
              </h1>

              <div class="form-group">
                <h4> <%= f.label :text_field, "Email:" %> </h4>
                <%= f.text_field :email, required: true, id: "user_email_field", class: 'form-control' %>
              </div>

              <div class="form-group">
                <h4> <%= f.label :text_field, "Password:" %> </h4>
                <%= f.password_field :password, required: true, id: "user_password_field", class: 'form-control' %>
              </div>

              <div class="form-group text-center">
                <%= f.submit "Log in", class: "btn btn-primary btn-lg" %>
              </div>

              <div class="form-group text-center">
                <%= link_to "/auth/facebook", class: "btn  btn-lg fb-btn", id: "sign_in" do %>
                  <h4><%=fa_icon("facebook-square")%>Login with Facebook</h4>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/partials/_register.html.erb
<div class="modal fade" id="register">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <div class="form">
            <%= form_for(:user, url: users_path, html: { id: "user-create-form" }) do |f| %>
              <h1 class="text-center">
                Register New Account
              </h1>

              <div class="form-group">
                <h4> <%= f.label :username_field, "Username:" %> </h4>
                <%= f.text_field :username, required: true, id: "user_username_field", class: 'form-control' %>
              </div>

              <div class="form-group">
                <h4> <%= f.label :text_field, "Password:" %> </h4>
                <%= f.password_field :password, id: "user_password__field", class: 'form-control' %>
              </div>

              <div class="form-group">
                <h4> <%= f.label :text_field, "Email:" %> </h4>
                <%= f.text_field :email, id: "user_email_field", class: 'form-control' %>
              </div>

              <div class="form-group">
                <h4><%= f.label "Post Image:" %></h4>
                <div id="preview-image">
                </div>
              </div>

              <div class="form-group">
                <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>
              </div>

              <div class="form-group text-center">
                <%= f.submit "Register", class: "btn btn-primary btn-lg" %>
              </div>

              <div class="form-group text-center">
                <%= link_to "/auth/facebook", class: "btn btn-primary btn-lg fb-btn", id: "sign_in" do %>
                  <i class="fa fa-facebook-square" aria-hidden="true"></i>
                  <h4>Sign-up with Facebook</h4>
                <% end %>
              </div>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>