config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :about, to: 'static_pages#about'
  root to: "landing#index"


  resources :items , only: [:index, :show, :edit]

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :ordered_items, only: [:add, :create]

  resources :orders, only: [:create]
  resources :carts, only: [:index, :add, :show, :edit, :remove]

  resources :checkouts, only: [:new, :create]


  post :add, to: 'carts#add'
  post :remove, to: 'carts#remove'

  match 'auth/:provider/callback', to: 'omniauth#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'omniauth#destroy', as: 'signout', via: [:get, :post]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  respond_to :js

  def index
    get_cart

    rescue => e
      flash[:danger] = "Your cart is empty, add some items first!"
      redirect_to root_path
  end

  def get_cart
    items = JSON.parse(cookies[:cart])
    total_price= 0.0;
    @items = []

    items.each do |k,v|
      item = Item.find_by(id: k)

      subprice =0.0;
      subprice = item.price * v.to_f
      total_price += subprice

      item.define_singleton_method(:quantities) { v }
      item.define_singleton_method(:subprice) {subprice}

      @items << item
    end

    total_price(total_price)
    return @items
  end

  def add
    if !cookies[:cart] #checks if an existing cart exists
      items = { params[:item_id] => cart_params[:quantity] }
    else
      items = JSON.parse(cookies[:cart])
      items[params[:item_id]] = cart_params[:quantity]
    end

    cookies[:cart] = JSON.generate(items)
  end

  def edit

  end

  def remove
    @items = JSON.parse(cookies[:cart])
    @items.delete(params[:id])

    if @items.empty?
      cookies.delete :cart
    else
      cookies[:cart] = JSON.generate(@items)
    end
    flash[:success] = "REMOVED items"
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:quantity)
  end

  def total_price(total_price)
    @total_price = total_price
  end
end

app/views/carts/add.html.erb
<%=
JSON.parse(cookies[:cart])
%>

app/views/carts/index.html.erb
<%@items.each do |item| %>

<div class="well well-sm" style="margin:2vh">


  <h5>
    <%=item.quantity%>
    <%=item.quantities%>
    <%=item.name%>
    <%=item.description%>
    <%=sprintf('%.2f', item.price)%>
    <%=item.subprice%>


    <%=form_for(:cart, url: edit_cart_path(id: item.id), method: :post, html: { id: "item-show-form" }) do |f| %>
      <div class="form-group">

        <h6>Quantity: <%= f.text_field :quantity, value:item.quantities, class: 'form-control quantity ' %>

        <%= f.submit "EDIT" %><h6>

      </div>
    <%end%>
    <%=link_to "X", remove_path(id: item.id), method: :post, data: {confirm: "Are you sure you want to remove #{item.name}?"}%>
  </h5>
</div>
<%end%>

  <div class="well well-sm" style="margin:2vh; text-align:right">
    TOTAL: <%=@total_price%>
  </div>

  <div  style="margin:2vh; text-align:right">
    <%=link_to "Checkout", new_checkout_path, class:"btn btn-lg success"%>
  </div>

app/views/carts/show.html.erb
<%@items.each do |item| %>

  <h5>
    <%=item.quantity%>
    <%=item.quantities%>
    <%=item.name%>
    <%=item.description%>
    <%=item.price%>
  </h5>

<%end%>
<%=@total_price%>

<a class="button primary back" href="/checkouts/new">
  <span>CHECKOUT</span>
</a>