config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get :about, to: 'static_pages#about'
  root to: "landing#index"


  resources :items , only: [:index, :show, :edit]

  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :ordered_items, only: [:add, :create]

  resources :orders, only: [:create]
  resources :carts, only: [:index, :add, :show, :edit, :remove]

  resources :checkouts, only: [:new, :create]


  post :add, to: 'carts#add'
  post :remove, to: 'carts#remove'

  match 'auth/:provider/callback', to: 'omniauth#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'omniauth#destroy', as: 'signout', via: [:get, :post]
end

app/models/item.rb
class Item < ApplicationRecord
  searchkick

  has_many :orders, through: :ordered_items
  has_many :ordered_items
  after_save :reindex_item

  mount_uploader :image, ImageUploader

  def reindex_item
    reindex
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :js

  def show
    @item = Item.find_by(id: params[:id])
  end

  def index
    params[:category] ||= ["T-Shirt", "Jacket", "Cap", ""]
    if params[:search] && params[:search].present?
      @items = Item.search(params[:search],
        where: { category: params[:category] })
    else
      @items = Item.where(category: params[:category])
    end
  end

  def update

  end

  private

  def item_params
    param.require(:item).permit(:name, :description, :price, :quantity, :image, :discount, :category)
  end
end

app/views/items/_items.html.erb
<% items.each do |item| %>
  <div class="col-sm-3 col-md-4">
    <div class="thumbnail">
      <% if item.image? %>
        <%= image_tag item.image, class: "img-settings img-responsive center-block" %>
      <% else %>
        <img src="..." alt="...">
      <% end %>
      <div class="caption">
        <h3><%=link_to item.name, item_path(item.id)%></h3>
        <p><%=item.description%></p>
        <h5><b>RM<%=sprintf('%.2f', item.price)%></b></h5>
        <p><%=link_to fa_icon("shopping-cart 1x"), add_path(item_id: item.id, cart:{quantity: 1}), method: :post, class: "btn btn-default" %>
          <a href="<%=item_path(item.id)%>" class="btn btn-primary" role="button">View</a> </p>
      </div>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<%= form_tag("/items", method: "get", remote: true, class: "search-bar text-center") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag(:search) %>
  <div class="dropdown">
    <button id="Categories_dropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Category
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="Categories_dropdown">
      <li><%= check_box_tag(:'category[]', "T-Shirt") %>
      <%= label_tag("T-Shirt") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'category[]', "Jacket") %>
      <%= label_tag("Jacket") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'category[]', "Cap") %>
      <%= label_tag("Cap") %></li>
    </ul>
  </div>
  <%= submit_tag("Search") %>
<% end %>

<div class="all-items">
  <%= render partial: "items", locals: { items: @items } %>
</div>

app/views/items/index.js.erb
 $('.all-items').html("<%=j render partial: 'items/items', locals: { items: @items } %>")

app/views/items/show.html.erb
<%=form_for(:cart, url: add_path(item_id: @item.id), method: :post, html: { id: "item-show-form" }) do |f| %>
  <div class="well item-container">
    <div class="item-item">
      <% if @item.image? %>
        <%= image_tag @item.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>

    <div class="item-item">
      <div class="form-group">
        <h3><%= f.label :title_field, @item.name %> </h3>
      </div>
      <div class="form-group">
        <h3><%= f.label :item_id, @item.id %> </h3>
      </div>
      <div class="">
        <span class="glyphicon glyphicon-search" aria-hidden="true">
      </div>
      <div class="form-group">
        <h4> <%= @item.description %> </h4>
      </div>

      <div class="form-group">
        <h6>In Stock:  <%= f.label :text_field, @item.quantity%> </h6>
      </div>

      <div class="form-group">
        <h6>Quantity: </h6><h6><%= f.text_field :quantity, class: 'form-control quantity ' %><h6>
      </div>

      <div class="form-group">
        <h4> Price: RM <%= @item.price %> </h4>
      </div>

      <div class="form-group">
        <%= f.submit "Buy Now", class: "btn btn-success btn-lg" %>
      </div>
    </div>
  </div>
<% end %>


<div class="additional-info">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Information</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Payments</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Shipping</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Returns</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content nav-justified">
    <div role="tabpanel" class="tab-pane active" id="home">THere sis something else here</div>
    <div role="tabpanel" class="tab-pane" id="profile">AThis is the profile</div>
    <div role="tabpanel" class="tab-pane" id="messages">This is the messages</div>
    <div role="tabpanel" class="tab-pane" id="settings">This is the settings</div>
  </div>

</div>